#!/bin/bash

set -e

function separator {
	echo '=========================='
}

now=`date +%s`

echo "Building the site: $now"
separator
hugo
separator

echo "Build the site and upload to Github"
git add docs
git commit -m "Built site $now"
git push origin master
separator

echo "Creating and pushing tag"
separator
git tag "$now"
git push --tags

separator
echo "Done!"
